exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert([
        { id: 1,
          item_name: 'You Animal - CD',
          seller_id: 2,
          category: 'Music',
          image_url: 'http://res.cloudinary.com/smfm/image/upload/v1515956504/alpca19egaok6acxomth.jpg',
          thumbnail_url: 'http://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1515956504/alpca19egaok6acxomth.jpg',
          external:'http://theriverarkansas.bandcamp.com',
          short: 'Second full-length album by the River Arkansas, an americana band based along Colorado\'s front range.',
          description:'Second full-length album by the River Arkansas, an americana band based along Colorado\'s front range. 11 tracks',
          price:'10.00',
          quantity:100,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 2,
          item_name: 'Get It While You Can',
          seller_id: 4,
          category: 'Writing',
          image_url: 'https://res.cloudinary.com/smfm/image/upload/v1516060393/ndhvof6etnqfwlcwxhxg.jpg',
          thumbnail_url: 'http://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516060393/ndhvof6etnqfwlcwxhxg.jpg',
          external:'http://www.perfectdaybooks.com/shop/get-it-while-you-can-by-nick-jaina-2010',
          short: 'Debut memoir by composer / songwriter Nick Jaina.',
          description:'When his beloved guitar is stolen, Nick Jaina finds himself untethered from the dream he’s pursued since he was sixteen. No matter how many albums he’s released or tours he’s led, he still can’t shake the feeling that he has failed at life. So the critically acclaimed, endlessly heartbroken singer-songwriter checks himself into a ten-day silent retreat. As those silent days unfold, Jaina attempts to rewire his own brain in a burst of unpredictable digressions and unsent love letters, musings on the miracles of science and the fallen heroes of popular music. Get It While You Can is a late-night ode to the pursuit of sanity.',
          price:'10.00',
          quantity:100,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 3,
          item_name: 'Patient Television',
          seller_id: 6,
          category: 'Art',
          image_url: 'https://res.cloudinary.com/smfm/image/upload/v1516060939/tm9bcrk7wxcdiwfiqhpr.jpg',
          thumbnail_url: 'https://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516060939/tm9bcrk7wxcdiwfiqhpr.jpg',
          external:'https://www.nursezines.com/',
          short: 'A zine of comics about strange world of a hospital from a nurse\s perspective.',
          description:'A peek into the strange world of a hospital from a nurse\s perspective. Comics and personal thoughts.',
          price:'5.00',
          quantity:25,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 4,
          item_name: 'Inside',
          seller_id: 6,
          category: 'Art',
          image_url: ' https://res.cloudinary.com/smfm/image/upload/v1516060992/zrvysn4gwovowixaqcm5.jpg',
          thumbnail_url: ' https://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516060992/zrvysn4gwovowixaqcm5.jpg',
          external:'https://www.nursezines.com/',
          short: 'Drawings and musings on cancer, hospitals, and nurse-patient relationships.',
          description:'Drawings and musings on cancer, hospitals, and nurse-patient relationships.',
          price:'5.00',
          quantity:25,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 5,
          item_name: 'Bone White Tea Set',
          seller_id: 7,
          category: 'Handmade',
          image_url: 'https://res.cloudinary.com/smfm/image/upload/v1516061250/bfdm0y0c8voi6ruvlnpl.jpg',
          thumbnail_url: 'https://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516061250/bfdm0y0c8voi6ruvlnpl.jpg',
          external:'http://sewandsopottery.bigcartel.com/product/bone-white-tea-set',
          short: 'Dishwasher, microwave, and oven safe. For loose leaf tea steeping.',
          description:'This tea set is cone ten gas fired, making it dishwasher, microwave, and oven safe. It is made for loose leaf tea steeping and the cups are 3"',
          price:'75.00',
          quantity:1,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 6,
          item_name: 'Bargain With The Devil 1',
          seller_id: 8,
          category: 'Art',
          image_url: 'https://res.cloudinary.com/smfm/image/upload/v1516061686/bkoghjgmc0p4zj6lay8n.jpg',
          thumbnail_url: 'https://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516061686/bkoghjgmc0p4zj6lay8n.jpg',
          external:'http://www.eleesule.com/store/p50/Bargain_with_the_Devil_%239.html',
          short: 'I painted this series as a reflection on current events in my life and the world at large',
          description:'From my 2017 show, Bargain with the Devil. I painted this series as a reflection on current events in my life and the world at large; it was a spin-off of my show the previous month (it was a busy summer for me, and very messy emotionally) about the stages of grief. One of my paintings in that series, from the bargaining stage, really resonated with me. I began to think of the different kinds of bargains we strike, from the heartsick invocations of grief to the small pieces of ourselves that we cut off to better fit someone\'s idea of us. Like I said, it was an emotionally messy year for me. So this series, because I had to keep working both to survive my brain and because I made a commitment, sprang from those thoughts. This piece is graphite on vellum with gold leaf, mounted on 13.5inX20in white matting paper.',
          price:'550.00',
          quantity:1,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        },
        { id: 7,
          item_name: 'Bargain With The Devil 2',
          seller_id: 8,
          category: 'Art',
          image_url: 'https://res.cloudinary.com/smfm/image/upload/v1516061779/beww1tmpitg03v514in2.jpg',
          thumbnail_url: 'https://res.cloudinary.com/smfm/image/upload/c_limit,h_60,w_90/v1516061779/beww1tmpitg03v514in2.jpg',
          external:'http://www.eleesule.com/store/',
          short:' I painted this series as a reflection on current events in my life and the world at large',
          description:'From my 2017 show, Bargain with the Devil. I painted this series as a reflection on current events in my life and the world at large; it was a spin-off of my show the previous month (it was a busy summer for me, and very messy emotionally) about the stages of grief. One of my paintings in that series, from the bargaining stage, really resonated with me. I began to think of the different kinds of bargains we strike, from the heartsick invocations of grief to the small pieces of ourselves that we cut off to better fit someone\'s idea of us. Like I said, it was an emotionally messy year for me. So this series, because I had to keep working both to survive my brain and because I made a commitment, sprang from those thoughts. This piece is graphite on vellum with gold leaf, mounted on 13.5inX20in white matting paper.',
          price:'550.00',
          quantity:1,
          created_at:'2018-01-12 17:26:12.813009-07',
          updated_at:'2018-01-12 17:26:12.813009-07'
        }
        ,
        // { id: 8,
        //   item_name: 'Danah Olivetree',
        //   seller_id: '123312398474406',
        //   category: true,
        //   image_url: '',
        //   thumbnail_url: '',
        //   external:'',
        //   description:'',
        //   price:'',
        //   quantity:'',
        //   sold:'',
        //   purchaser_id:'',
        //   shipped: '',
        //   created_at:'',
        //   updated_at:''
        // },
        // { id: 9,
        //   item_name: 'Danah Olivetree',
        //   seller_id: '123312398474406',
        //   category: true,
        //   image_url: '',
        //   thumbnail_url: '',
        //   external:'',
        //   description:'',
        //   price:'',
        //   quantity:'',
        //   sold:'',
        //   purchaser_id:'',
        //   shipped: '',
        //   created_at:'',
        //   updated_at:''
        // },
        // { id: 10,
        //   item_name: 'Danah Olivetree',
        //   seller_id: '123312398474406',
        //   category: true,
        //   image_url: '',
        //   thumbnail_url: '',
        //   external:'',
        //   description:'',
        //   price:'',
        //   quantity:'',
        //   sold:'',
        //   purchaser_id:'',
        //   shipped: '',
        //   created_at:'',
        //   updated_at:''
        // },

      ]).then(() => {
               return knex.raw("SELECT setval('products_id_seq', (SELECT MAX(id) FROM products));")
                 })
         });
     };
